### ISSUE TITLE
Wizard101 Android Application

### ISSUE THREAD

**Issue by lazic7** [R-unic/WizWikiAPI#1]
Dear @R-unic,

Sorry for submitting a new issue on your project, I'm trying to establish contact with you.
I'm student from Croatia, and currently I'm trying to develop an android application that might be used by wizard101 community in the future.

I was in search for an API that would provide me information about bosses and spells, then I stumble upon your github repository. I was wondering if I'm allowed to use your API, and if so I would like you to explain me in short how does it work.

Main reason for starting this project is because i was given a task on university to develop an android app... also got an idea that i might contribute to the community. Application will be developed voluntarily unless there are other ideas or ways to cooperate.

I hope you understand my reason for submitting an issue on your repository.
Thank you for your consideration and time.

**Comment by R-unic** [comment]
No worries whatsoever about submitting an issue! I'd be honored if you used my API for your project, so yes you absolutely can! It doesn't currently have any documentation on it's endpoints, but it's easy to figure out. The API links almost directly to the Wizard101 Wiki, so anything you might do on there will most likely work. For example: `/spells/Tower_Shield`.

Remember that the API is unfinished, and all endpoints that have been or will be added are on the README. Since you will be working on this project, I will try to finish some of the more important endpoints for you, such as items.

Thank you for inquiring, and especially thank you for letting me know about your project! I hope it turns out well, and let me know when it's done!

If you have any further questions or concerns, you can go ahead and add me on Discord `@_runic_`.
